// Broad common-English dictionary for Clear the String acceptance.
//
// It loads the same curated list that backs Change by One (/words-cbo.json,
// generated by scripts/build-cbo-words.mjs) so common words such as "hands" and
// "flood" are accepted even though public/data/words.json is missing many
// inflected forms. The two lists come from the same curated source family.

let commonSet: Set<string> | null = null;
let byLength: Record<number, string[]> = {};
let loadPromise: Promise<void> | null = null;

export async function loadEnglishCommon(): Promise<void> {
  if (commonSet) return;
  if (loadPromise) return loadPromise;

  loadPromise = (async () => {
    const res = await fetch('/words-cbo.json');
    if (!res.ok) throw new Error('Failed to load common word list');
    const data: Record<string, string[]> = await res.json();
    const set = new Set<string>();
    const byLen: Record<number, string[]> = {};
    for (const [key, words] of Object.entries(data)) {
      const len = Number(key);
      if (!Number.isFinite(len) || !Array.isArray(words)) continue;
      const arr: string[] = [];
      for (const w of words) {
        const lw = w.toLowerCase();
        set.add(lw);
        arr.push(lw);
      }
      byLen[len] = arr;
    }
    commonSet = set;
    byLength = byLen;
  })();

  return loadPromise;
}

export function isCommonEnglishWord(word: string): boolean {
  return commonSet ? commonSet.has(word.toLowerCase()) : false;
}

export function getCommonEnglishWordsByLength(length: number): string[] {
  return byLength[length] ?? [];
}

export function isEnglishCommonLoaded(): boolean {
  return commonSet !== null;
}
