// Puzzle generation and validation for ORDERLE and FERMI
// Generates a full year of puzzles following the weekly rotation schedule

export interface OrderlePuzzle {
  category: string;
  rule: string;
  items: string[];
  reveal: string;
  citation: string;
  difficulty: string;
  reverse?: boolean;
}

export interface FermiPuzzle {
  category: string;
  units: string;
  prompt: string;
  answer: number;
  reveal: string;
  citation: string;
  difficulty: string;
}

// ─── Puzzle banks ────────────────────────────────────────────────────────────

const ORDERLE_BANK: OrderlePuzzle[] = [
  // Items are interleaved across categories (deterministic round-robin in a fixed
  // category order) so consecutive daily puzzles never cluster in one category.
  // Every puzzle is retained; only its position in the bank changes.
  { category:"cooking", rule:"Making French press coffee", items:["grind the beans","boil water","add grounds to press","pour hot water","steep 4 minutes","press and pour"], reveal:"Grind size controls extraction speed; steeping controls strength; pressing stops extraction. Coarse grind + 4-minute steep = balanced cup.", citation:"https://www.stumptowncoffee.com/pages/brew-guide-french-press", difficulty:"easy" },
  { category:"science", rule:"Water cycle", items:["evaporation","condensation","precipitation","runoff","collection","evaporation (repeat)"], reveal:"Solar-driven distillation: Sun evaporates water, clouds condense it, rain returns it. Same molecules cycle for billions of years.", citation:"https://www.usgs.gov/special-topics/water-science-school/science/water-cycle", difficulty:"easy" },
  { category:"history", rule:"French Revolution (1789–1799)", items:["Estates-General convenes","Tennis Court Oath","Storming of the Bastille","Declaration of the Rights of Man","Reign of Terror","Napoleon's coup"], reveal:"Slide from constitutional reform to radical terror to military dictatorship -- causes, not dates.", citation:"https://www.britannica.com/event/French-Revolution", difficulty:"medium" },
  { category:"grammar", rule:"English adjective order (OSASCOMP)", items:["opinion","size","age","shape","color"], reveal:"English has a mandatory adjective hierarchy. Native speakers apply it unconsciously and instantly reject violations.", citation:"https://dictionary.cambridge.org/grammar/british-grammar/adjectives-order", difficulty:"medium" },
  { category:"everyday", rule:"Sending a letter", items:["write the letter","fold it","seal the envelope","address it","stamp it","post it"], reveal:"Fold before sealing, address before stamping, stamp before posting. An unstamped, unaddressed envelope will never arrive.", citation:"https://www.usps.com/ship/letters.htm", difficulty:"easy" },
  { category:"mixed", rule:"Solar system planets by distance from Sun", items:["Mercury","Venus","Earth","Mars","Jupiter","Saturn","Uranus","Neptune"], reveal:"Inner rocky planets -> asteroid belt -> outer gas giants -> ice giants. My Very Educated Mother Just Served Us Noodles.", citation:"https://solarsystem.nasa.gov/planets/overview/", difficulty:"medium" },
  { category:"biology", rule:"Taxonomic ranks (broadest to most specific)", items:["domain","kingdom","phylum","class","order","family","genus","species"], reveal:"Dear King Philip Came Over For Good Soup. Humans: Eukarya, Animalia, Chordata, Mammalia, Primates, Hominidae, Homo, sapiens.", citation:"https://www.britannica.com/science/taxonomy", difficulty:"medium" },
  { category:"cooking", rule:"Baking bread from scratch", items:["mix flour water yeast salt","knead the dough","let it rise","punch it down","shape the loaf","bake it"], reveal:"Yeast produces CO₂ during fermentation; kneading develops gluten; punching redistributes yeast for second rise.", citation:"https://www.kingarthurbaking.com/learn/guides/bread", difficulty:"easy" },
  { category:"science", rule:"The scientific method", items:["ask a question","do background research","construct a hypothesis","test with an experiment","analyze data","communicate results"], reveal:"Iterative -- results lead to new questions. A hypothesis must be falsifiable to be scientific.", citation:"https://www.sciencebuddies.org/science-fair-projects/science-fair/steps-of-the-scientific-method", difficulty:"medium" },
  { category:"history", rule:"History of the Roman Republic", items:["Overthrow of the monarchy","Creation of the Senate","Punic Wars against Carthage","Gracchi reforms","Caesar crosses the Rubicon","Augustus becomes first emperor"], reveal:"The Republic expanded through war, collapsed from internal inequality and ambition. The Rubicon was the point of no return.", citation:"https://www.britannica.com/place/ancient-Rome", difficulty:"medium" },
  { category:"grammar", rule:"Order of adverbs: manner, place, time", items:["manner (how)","place (where)","time (when)"], reveal:"When several adverbs follow the verb they fall in the order how, then where, then when -- ‘She sang beautifully (manner) in the hall (place) last night (time).’ Reordering them sounds wrong to a native ear.", citation:"https://dictionary.cambridge.org/grammar/british-grammar/adverbs-and-adverb-phrases-position", difficulty:"medium" },
  { category:"everyday", rule:"Washing laundry", items:["sort clothes by colour","load the machine","add detergent","select cycle and temperature","start the wash","transfer to dryer"], reveal:"Sorting prevents colour bleeding. Cold water saves energy and protects fabrics. Too much detergent leaves residue.", citation:"https://www.cleaninginstitute.org/cleaning-tips/clothes/laundry-basics", difficulty:"easy" },
  { category:"mixed", rule:"Units of digital storage, smallest to largest", items:["bit","byte","kilobyte","megabyte","gigabyte","terabyte"], reveal:"Eight bits to a byte. Storage is decimal (1,000) while memory is binary (1,024), which is why a '500 GB' drive shows up as roughly 465 GB in an operating system.", citation:"https://www.nist.gov/pml/owm/metric-si-prefixes", difficulty:"easy" },
  { category:"biology", rule:"Levels of organisation in the body", items:["atom","molecule","organelle","cell","tissue","organ","organ system","organism"], reveal:"Atoms form molecules, molecules form organelles (like mitochondria), organelles build cells, cells make tissues, tissues form organs, organs work in systems.", citation:"https://www.britannica.com/science/biological-organization", difficulty:"medium" },
  { category:"cooking", rule:"Making a cup of tea (British method)", items:["boil fresh water","warm the teapot","add tea leaves","pour boiling water","steep 3–5 minutes","pour through strainer"], reveal:"Freshly boiled water has more dissolved oxygen for better flavour. Warming the pot prevents temperature drop.", citation:"https://www.tea.co.uk/how-to-brew-tea", difficulty:"easy" },
  { category:"science", rule:"Path of food through the body", items:["mouth","esophagus","stomach","small intestine","large intestine","rectum"], reveal:"Mechanical breakdown -> chemical digestion -> absorption -> water reabsorption -> storage. Small intestine does ~90% of nutrient absorption.", citation:"https://www.niddk.nih.gov/health-information/digestive-diseases/digestive-system-how-it-works", difficulty:"easy" },
  { category:"history", rule:"World War II (1939–1945)", items:["Germany invades Poland","Fall of France","Pearl Harbor attack","D-Day landings","Hiroshima bomb","Japan surrenders"], reveal:"Escalated from European to global war with Pearl Harbor. D-Day opened the Western Front; atomic bombs ended the Pacific war.", citation:"https://www.britannica.com/event/World-War-II", difficulty:"medium" },
  { category:"grammar", rule:"Clause elements in normal English word order", items:["subject","verb","object","adverbial (time or place)"], reveal:"English is a subject-verb-object language: ‘The child threw the ball in the garden.’ The order carries the meaning that case endings carry in many other languages -- move the words and you change who did what to whom.", citation:"https://dictionary.cambridge.org/grammar/british-grammar/word-order-structures", difficulty:"easy" },
  { category:"everyday", rule:"Changing a car tyre", items:["park on flat ground","loosen lug nuts slightly","jack up the car","remove lug nuts and tyre","mount the spare tyre","tighten lug nuts in star pattern"], reveal:"Loosen nuts before jacking (wheel needs ground friction). Star-pattern tightening prevents warping the brake rotor.", citation:"https://www.bridgestonetire.com/learn/maintenance/how-to-change-a-flat-tire/", difficulty:"easy" },
  { category:"mixed", rule:"Periods of the Mesozoic Era, earliest to latest", items:["Triassic","Jurassic","Cretaceous"], reveal:"Triassic, Jurassic, Cretaceous — the three periods that together make up the Mesozoic, ending 66 million years ago with the impact that ended the non-avian dinosaurs.", citation:"https://www.britannica.com/science/geologic-time", difficulty:"medium" },
  { category:"biology", rule:"Levels of a food chain, from the Sun to a decomposer", items:["the Sun (energy source)","producer (a green plant)","primary consumer (a herbivore)","secondary consumer (a carnivore)","apex predator","decomposer"], reveal:"Energy passes from the Sun to the producers and up through the consumers, losing most of itself as heat at every step -- only about a tenth reaches the next level. Decomposers finally return the nutrients to the soil.", citation:"https://www.britannica.com/science/food-chain", difficulty:"easy" },
  { category:"cooking", rule:"Making pasta from scratch", items:["make a flour well","crack eggs into the well","slowly incorporate flour","knead until smooth","rest the dough 30 min","roll and cut"], reveal:"The flour well contains eggs; slow incorporation prevents lumps. Resting relaxes gluten for easier rolling.", citation:"https://www.seriouseats.com/fresh-egg-pasta", difficulty:"easy" },
  { category:"science", rule:"Life cycle of a star (Sun-like)", items:["nebula","protostar","main sequence star","red giant","planetary nebula","white dwarf"], reveal:"Stars spend ~90% of life on main sequence fusing hydrogen. Our Sun is halfway through its 10-billion-year run.", citation:"https://imagine.gsfc.nasa.gov/science/objects/stars1.html", difficulty:"medium" },
  { category:"history", rule:"American Revolution (1765–1783)", items:["Stamp Act passed","Boston Tea Party","First Continental Congress","Declaration of Independence","Battle of Yorktown","Treaty of Paris"], reveal:"Taxation without representation -> protest -> organized resistance -> declaration -> war -> victory. Eight years from Congress to treaty.", citation:"https://www.britannica.com/event/American-Revolution", difficulty:"medium" },
  { category:"grammar", rule:"Tense timeline (past to future)", items:["past perfect","simple past","present perfect","simple present","simple future"], reveal:"Ordered by the time each tense points to, earliest first: past perfect (an event completed before another past event), simple past, present perfect (past reaching into now), simple present, simple future.", citation:"https://www.grammarly.com/blog/verb-tenses/", difficulty:"medium" },
  { category:"everyday", rule:"Washing your hands", items:["wet your hands with clean running water and apply soap","lather the backs of your hands, between the fingers and under the nails","scrub for at least 20 seconds","rinse well under clean running water","dry with a clean towel or an air dryer"], reveal:"The order is the CDC’s five steps: wet, lather, scrub, rinse, dry. The step most people skip is the twenty seconds of scrubbing -- hum ‘Happy Birthday’ twice as a timer.", citation:"https://www.cdc.gov/clean-hands/about/index.html", difficulty:"easy" },
  { category:"biology", rule:"One heartbeat through the heart's chambers", items:["deoxygenated blood enters the right atrium","it flows into the right ventricle","the right ventricle pumps it to the lungs","oxygenated blood returns to the left atrium","it flows into the left ventricle","the left ventricle pumps it out through the aorta"], reveal:"The left ventricle has a thicker wall than the right because it drives blood through the entire body rather than only to the lungs. Valves between the chambers stop any backflow.", citation:"https://www.nhlbi.nih.gov/health/heart", difficulty:"medium" },
  { category:"cooking", rule:"Making sushi rice", items:["rinse rice until water runs clear","cook rice","mix rice vinegar sugar salt","cool rice slightly","fold seasoning into rice","fan rice to glossy finish"], reveal:"Rinsing removes excess starch. Fanning while folding cools rice and gives characteristic glossy sheen.", citation:"https://www.justonecookbook.com/how-to-make-sushi-rice/", difficulty:"easy" },
  { category:"science", rule:"Photosynthesis process", items:["sunlight absorbed by chlorophyll","water split into H and O","oxygen released as a by-product","CO₂ enters through stomata","Calvin cycle fixes carbon","glucose produced"], reveal:"Light reactions split water to make ATP; the Calvin cycle uses that ATP to build glucose. Oxygen is a waste product released when water is split, not at the end of the process.", citation:"https://www.britannica.com/science/photosynthesis", difficulty:"medium" },
  { category:"history", rule:"Development of the internet", items:["ARPANET (1969)","TCP/IP protocol (1983)","World Wide Web (1991)","Google search (1998)","Facebook (2004)","iPhone (2007)"], reveal:"Each step is a layer: plumbing -> protocol -> content -> discovery -> social -> mobile. The internet is a stack.", citation:"https://www.internetsociety.org/internet/history-internet/", difficulty:"medium" },
  { category:"grammar", rule:"Sentence building (simplest to most complex)", items:["independent clause","compound sentence","complex sentence","compound-complex sentence"], reveal:"A clause has subject + verb. Compound = two independent clauses joined. Complex = independent + dependent. Compound-complex = three or more.", citation:"https://academicguides.waldenu.edu/writingcenter/grammar/sentencestructure", difficulty:"easy" },
  { category:"everyday", rule:"Sorting household recycling", items:["check what your local service accepts","rinse containers and remove the lids","keep paper and card clean and dry","separate glass, metal, plastic and paper","put each material in the correct bin","put the bins out before collection"], reveal:"Sorting works because the materials are processed separately. Rinsing stops food residue contaminating a whole load, and paper has to stay dry or it cannot be recycled.", citation:"https://www.epa.gov/recycle", difficulty:"easy" },
  { category:"cooking", rule:"Making pancakes from scratch", items:["mix dry ingredients","whisk wet ingredients","combine wet and dry","heat the griddle","pour batter","flip when bubbles form"], reveal:"Don't overmix -- lumps are fine. Bubbles forming on top = ready to flip. First pancake is always the tester.", citation:"https://www.kingarthurbaking.com/recipes/simply-perfect-pancakes-recipe", difficulty:"easy" },
  { category:"science", rule:"Rock cycle", items:["magma cools","igneous rock forms","weathering and erosion","sediment deposited","compaction and cementation","sedimentary rock"], reveal:"Igneous -> sedimentary -> metamorphic -> melt back to magma. Any rock can become any other -- a true cycle, not a line.", citation:"https://www.britannica.com/science/rock-cycle", difficulty:"medium" },
  { category:"history", rule:"Space Race (1957–1969)", items:["Sputnik launched (October 1957)","Yuri Gagarin orbits Earth (April 1961)","JFK’s Moon speech (May 1961)","Apollo 8 orbits Moon (December 1968)","Apollo 11 lands on Moon (July 1969)"], reveal:"From first satellite to first Moon landing in just 12 years. The race was driven by Cold War competition -- but the technology legacy is universal.", citation:"https://www.britannica.com/science/space-exploration", difficulty:"medium" },
  { category:"grammar", rule:"Degrees of comparison: positive, comparative, superlative", items:["positive (tall)","comparative (taller)","superlative (tallest)"], reveal:"An adjective moves through three degrees: the positive names the quality, the comparative sets one thing against another (taller than), and the superlative places one above all the rest (the tallest).", citation:"https://dictionary.cambridge.org/grammar/british-grammar/adjectives-comparative-and-superlative", difficulty:"easy" },
  { category:"everyday", rule:"Passing through airport security", items:["check in and hand over any checked bags","join the screening lane and show your boarding pass and ID","place laptops and liquids in their own trays","empty your pockets and remove belts and jackets","walk through the metal detector or body scanner","collect your belongings and put your shoes back on"], reveal:"The sequence is forced by the checkpoint: anything that must be screened separately goes in a tray, then you are screened, then you pick your things up on the far side. Liquids follow the 3-1-1 rule.", citation:"https://www.tsa.gov/travel/security-screening", difficulty:"easy" },
  { category:"cooking", rule:"Roasting a chicken", items:["preheat oven to 425°F","pat chicken dry","season inside and out","truss the legs","roast breast-side up","rest 15 min before carving"], reveal:"Dry skin = crispy. High initial heat renders fat. Resting redistributes juices -- cutting immediately loses them.", citation:"https://www.seriouseats.com/butterflied-roasted-chicken-with-quick-jus-recipe", difficulty:"easy" },
  { category:"science", rule:"Human evolution timeline", items:["Ardipithecus (4.4 mya)","Australopithecus afarensis (Lucy)","Homo habilis","Homo erectus","Homo neanderthalensis","Homo sapiens"], reveal:"Bipedalism first, then bigger brains, then tools, then fire. Neanderthals were contemporaries, not ancestors.", citation:"https://humanorigins.si.edu/evidence/human-family-tree", difficulty:"hard" },
  { category:"history", rule:"Industrial Revolution milestones", items:["Spinning jenny invented (1764)","Watt's steam engine (1776)","First steam locomotive (1804)","Telegraph invented (1837)","Bessemer steel process (1856)","First telephone call (1876)"],reveal:"Textile mechanisation -> steam power -> transport revolution -> instant communication -> mass production. Each innovation enabled the next.", citation:"https://www.britannica.com/event/Industrial-Revolution", difficulty:"medium" },
  { category:"grammar", rule:"Determiners before a noun, in order", items:["predeterminer (all, both, half)","central determiner (the, a, this, my)","postdeterminer (numbers and ordinals)","the noun"], reveal:"Determiners stack in a fixed order: ‘all (predeterminer) the (central determiner) three (postdeterminer) boys (noun)’. Swap the slots and the phrase becomes ungrammatical.", citation:"https://learnenglish.britishcouncil.org/grammar/english-grammar-reference/determiners-quantifiers", difficulty:"medium" },
  { category:"everyday", rule:"Setting up a new phone", items:["charge it to 100%","connect to Wi-Fi","sign in to your account","restore from backup (or start fresh)","set up biometrics (face/fingerprint)","install essential apps"], reveal:"Charging first prevents setup interruptions. Restoring from backup saves hours. Biometrics before app install -- security first.", citation:"https://support.apple.com/en-us/HT202033", difficulty:"easy" },
  { category:"cooking", rule:"Making chocolate chip cookies", items:["cream butter and sugar","add eggs and vanilla","mix in dry ingredients","fold in chocolate chips","scoop onto baking sheet","bake at 350°F for 10–12 min"], reveal:"Creaming incorporates air for lift. Chilling dough before baking deepens flavour and prevents spreading.", citation:"https://www.kingarthurbaking.com/recipes/chocolate-chip-cookies-recipe", difficulty:"easy" },
  { category:"science", rule:"DNA to protein (central dogma)", items:["DNA transcription","mRNA processing","mRNA leaves nucleus","ribosome binds mRNA","tRNA brings amino acids","polypeptide chain forms"], reveal:"Transcription copies DNA to mRNA; translation reads mRNA to build protein. One gene -> one polypeptide -> folded protein.", citation:"https://www.genome.gov/genetics-glossary/Central-Dogma", difficulty:"hard" },
  { category:"history", rule:"Civil Rights Movement (US)", items:["Brown v. Board of Education (1954)","Montgomery Bus Boycott (1955)","March on Washington (1963)","Civil Rights Act (1964)","Voting Rights Act (1965)","Fair Housing Act (1968)"],reveal:"Legal challenges -> grassroots protest -> mass mobilisation -> federal legislation. Each law built on the momentum of the previous.", citation:"https://www.britannica.com/event/American-civil-rights-movement", difficulty:"medium" },
  { category:"grammar", rule:"Writing process (academic)", items:["brainstorm and research","create an outline","write the first draft","revise for structure","edit for grammar and style","proofread"], reveal:"Writing = rewriting. The first draft is for getting ideas down; revision is where the real writing happens. Never edit while drafting.", citation:"https://owl.purdue.edu/owl/general_writing/the_writing_process/index.html", difficulty:"easy" },
  { category:"everyday", rule:"Opening a bank account", items:["decide whether you need a checking or a savings account","compare the fees and features of a few banks","gather your photo ID and proof of address","apply online or at a branch","make the minimum opening deposit","set up online banking and a debit card"], reveal:"Identity and address checks come before anything is opened, which is why banks ask for documents up front. Comparing fees first is what separates a good account from an expensive one.", citation:"https://www.consumerfinance.gov/consumer-tools/bank-accounts/", difficulty:"easy" },
  { category:"cooking", rule:"Brewing pour-over coffee", items:["rinse the filter","add ground coffee","bloom with hot water (30s)","pour in slow circles","let it drain completely","serve immediately"], reveal:"Blooming releases CO₂ for even extraction. Slow circular pour prevents channeling. Drink within minutes -- coffee oxidises.", citation:"https://www.stumptowncoffee.com/pages/brew-guide-pour-over", difficulty:"easy" },
  { category:"science", rule:"Cell division (mitosis)", items:["interphase (DNA replicates)","prophase (chromosomes condense)","metaphase (align at equator)","anaphase (sister chromatids separate)","telophase (nuclear envelope reforms)","cytokinesis (cell splits)"], reveal:"Mitosis produces two identical daughter cells. Interphase is where the cell spends 90% of its life -- it's not a 'resting' phase.", citation:"https://www.britannica.com/science/mitosis", difficulty:"medium" },
  { category:"history", rule:"Renaissance timeline", items:["Gutenberg's printing press (1440)","Columbus reaches Americas (1492)","da Vinci paints Mona Lisa (1503)","Michelangelo's David (1504)","Luther's 95 Theses (1517)","Copernicus publishes heliocentric model (1543)"],reveal:"Printing press democratised knowledge -> exploration expanded worldview -> art captured humanism -> Reformation challenged authority -> science redefined the cosmos.", citation:"https://www.britannica.com/event/Renaissance", difficulty:"medium" },
  { category:"grammar", rule:"Verb phrase order: modal to main verb", items:["modal (can, might, will)","perfect (have)","progressive (be)","main verb"], reveal:"The order inside a verb phrase is fixed: ‘She might (modal) have (perfect) been (progressive) waiting (main verb).’ Cambridge sets it out left to right, and the main verb always comes last.", citation:"https://dictionary.cambridge.org/grammar/british-grammar/verb-phrases", difficulty:"medium" },
  { category:"everyday", rule:"Registering to vote in the United States", items:["check your state’s registration deadline","fill in the voter-registration form online, by post or in person","submit it before the deadline","confirm your registration was accepted","go to your polling place on election day","show any required ID and cast your ballot"], reveal:"Registration has to be done before the deadline, and it is worth confirming it was accepted. On election day the only steps left are showing ID where required and casting the ballot.", citation:"https://www.usa.gov/register-to-vote", difficulty:"easy" },
  { category:"cooking", rule:"Making homemade pizza", items:["activate yeast in warm water","mix and knead dough","let dough rise 1 hour","stretch into a round","add sauce and toppings","bake at highest oven temp"], reveal:"High heat mimics a pizza oven (900°F). Stretch by hand -- rolling pins degas the dough. Less is more with toppings.", citation:"https://www.seriouseats.com/basic-pizza-dough-recipe", difficulty:"easy" },
  { category:"science", rule:"The carbon cycle", items:["CO₂ in atmosphere","plants absorb CO₂ (photosynthesis)","animals eat plants","respiration releases CO₂","decomposition returns carbon to soil","fossil fuel burning adds CO₂"], reveal:"Carbon moves between atmosphere, biosphere, oceans, and geosphere. Human burning of fossil fuels has increased atmospheric CO₂ by ~50% since 1750.", citation:"https://www.britannica.com/science/carbon-cycle", difficulty:"medium" },
  { category:"history", rule:"Ancient Egypt timeline (Old to New Kingdom)", items:["Great Pyramid built (2560 BCE)","Middle Kingdom begins (2055 BCE)","Hyksos invasion (1650 BCE)","New Kingdom begins (1550 BCE)","Tutankhamun reigns (1332 BCE)","Ramesses II reigns (1279 BCE)"],reveal:"Old Kingdom = pyramid age. Middle Kingdom = stability. Hyksos introduced chariots. New Kingdom = empire and famous pharaohs -- three distinct eras over 1,300 years.", citation:"https://www.britannica.com/place/ancient-Egypt", difficulty:"hard" },
  { category:"grammar", rule:"Conditional sentences (most certain to least)", items:["zero conditional (facts)","first conditional (real future)","second conditional (unlikely present)","third conditional (impossible past)","mixed conditional"], reveal:"If + present, present = always true. If + present, will = possible. If + past, would = hypothetical. If + past perfect, would have = regret.", citation:"https://www.grammarly.com/blog/conditional-sentences/", difficulty:"hard" },
  { category:"everyday", rule:"Planning a dinner party", items:["choose a date and invite guests","plan the menu (account for dietary needs)","shop for ingredients (day before)","prep what you can in advance","set the table and arrange seating","cook and serve -- don't apologise"], reveal:"Prep in advance = less stress. Seating arrangement shapes conversation. Never apologise for the food -- guests don't notice what you think went wrong.", citation:"https://www.bonappetit.com/story/how-to-host-a-dinner-party", difficulty:"easy" },
  { category:"cooking", rule:"Knife skills: vegetable prep order", items:["wash all vegetables","peel what needs peeling","trim ends and bad spots","slice into planks","cut planks into strips","dice strips into cubes"], reveal:"Clean -> peel -> trim -> slice -> strip -> dice. This order minimises mess and maximises control. Sharp knife = safer than dull.", citation:"https://www.seriouseats.com/knife-skills-the-basics", difficulty:"easy" },
  { category:"science", rule:"Electromagnetic spectrum (lowest to highest energy)", items:["radio waves","microwaves","infrared","visible light","ultraviolet","X-rays","gamma rays"], reveal:"Longer wavelength = lower energy. Radio waves can be kilometres long; gamma rays are smaller than an atom. Only visible light can our eyes detect.", citation:"https://imagine.gsfc.nasa.gov/science/toolbox/emspectrum1.html", difficulty:"hard" },
  { category:"history", rule:"Seven Wonders of the Ancient World (chronological)", items:["Great Pyramid of Giza (2560 BCE)","Hanging Gardens of Babylon (c. 600 BCE)","Temple of Artemis at Ephesus (c. 550 BCE)","Statue of Zeus at Olympia (c. 435 BCE)","Mausoleum at Halicarnassus (c. 350 BCE)","Colossus of Rhodes (completed 280 BCE)","Lighthouse of Alexandria (completed 247 BCE)"], reveal:"The order runs by construction date. The Temple of Artemis was built about a century before the Statue of Zeus at Olympia -- the pair most often listed the wrong way round. Only the Great Pyramid, the oldest, still stands.", citation:"https://en.wikipedia.org/wiki/Seven_Wonders_of_the_Ancient_World", difficulty:"hard" },
  { category:"grammar", rule:"Story structure (classic narrative arc)", items:["exposition","inciting incident","rising action","climax","falling action","resolution"], reveal:"Almost every story you've ever loved follows this arc. It's not a formula -- it's a description of how tension naturally builds and releases.", citation:"https://www.masterclass.com/articles/elements-of-a-story", difficulty:"easy" },
  { category:"everyday", rule:"Steps to buy a house", items:["check credit score and get pre-approved","find a real estate agent","tour homes and make an offer","get a home inspection","secure final mortgage approval","close the deal and get the keys"], reveal:"Pre-approval shows sellers you're serious. Inspection protects you from hidden problems. Closing is signing a mountain of paperwork.", citation:"https://www.consumerfinance.gov/owning-a-home/", difficulty:"easy" },
  { category:"cooking", rule:"Making a basic vinaigrette", items:["whisk vinegar with salt until the salt dissolves","whisk in a little mustard","slowly stream in the oil while whisking","taste and adjust the balance","dress the salad just before serving"], reveal:"Mustard is an emulsifier: it keeps the oil and vinegar suspended instead of separating. Salting the vinegar first seasons the whole dressing evenly.", citation:"https://www.seriouseats.com/", difficulty:"easy" },
  { category:"science", rule:"Geological time scale (earliest to most recent)", items:["Hadean Eon","Archean Eon","Proterozoic Eon","Paleozoic Era","Mesozoic Era","Cenozoic Era"], reveal:"Earth is 4.6 billion years old. Humans appeared in the last ~0.007% of that. If Earth's history were a 24-hour clock, humans arrive at 23:59:58.", citation:"https://www.britannica.com/science/geologic-time", difficulty:"hard" },
  { category:"history", rule:"Ancient Greek philosophers (chronological)", items:["Thales (624 BCE)","Pythagoras (570 BCE)","Socrates (470 BCE)","Plato (428 BCE)","Aristotle (384 BCE)","Epicurus (341 BCE)"],reveal:"Thales asked what stuff is made of; Pythagoras found numbers in nature; Socrates questioned everything; Plato wrote it down; Aristotle systematised it all.", citation:"https://www.britannica.com/topic/Greek-philosophy", difficulty:"hard" },
  { category:"grammar", rule:"Ordering the parts of a formal letter", items:["sender's address","date","recipient's address","salutation","body of the letter","closing and signature"], reveal:"The block ordering is not arbitrary: the reader learns who is writing, when, and to whom before reading a word of the argument. Everything after the signature — enclosures, postscripts — sits outside the main body.", citation:"https://www.britannica.com/", difficulty:"easy" },
  { category:"everyday", rule:"Tying a shoelace with the loop method", items:["cross the two laces","pass one lace under the other and pull tight","form a loop with each lace","cross the loops over each other","push one loop through the hole","pull both loops to tighten"], reveal:"The 'bunny ears' method works for children, but the same knot has a faster one-loop variant. A knot that comes undone is usually an imbalance knot — the starting cross is backwards.", citation:"https://www.britannica.com/", difficulty:"easy" },
  { category:"cooking", rule:"Resting and carving a roast", items:["take the roast out of the oven","rest it for 10 to 20 minutes","move it to a board with a juice channel","slice across the grain","serve straight away"], reveal:"Resting lets the muscle fibres relax and reabsorb juices; carving too early loses them to the board. Cutting across the grain shortens the tough fibres.", citation:"https://www.seriouseats.com/", difficulty:"easy" },
  { category:"science", rule:"Life cycle of a butterfly", items:["egg","larva (caterpillar)","pupa (chrysalis)","adult butterfly"], reveal:"Complete metamorphosis: the caterpillar's tissues are largely rebuilt inside the pupa. A monarch takes about a month from egg to adult.", citation:"https://www.britannica.com/", difficulty:"easy" },
  { category:"history", rule:"The first seventy-three years of human flight", items:["the Wright brothers' first powered flight (1903)","Lindbergh crosses the Atlantic alone (1927)","the first jet airliner enters service (1952)","the Boeing 747 enters service (1970)","Concorde enters passenger service (1976)"], reveal:"From a 12-second hop to a scheduled supersonic service in 73 years. Two of those aircraft -- the 747 and Concorde -- were designed in the same decade and flew for the next half century.", citation:"https://www.britannica.com/", difficulty:"medium" },
  { category:"grammar", rule:"Grammatical person: first, second, third", items:["first person singular (I)","first person plural (we)","second person (you)","third person singular (he, she, it)","third person plural (they)"], reveal:"Grammatical person is numbered outwards from the speaker: first person is the speaker (I, we), second person the person addressed (you), and third person everyone else (he, she, it, they). The numbering is a convention, not a ranking.", citation:"https://en.wikipedia.org/wiki/Grammatical_person", difficulty:"medium" },
  { category:"everyday", rule:"Renewing a passport", items:["check the expiry date and the lead time","get a compliant photograph","complete the application form","pay the fee","submit the application","wait for processing, then collect or receive it"], reveal:"Many countries require the passport to be valid for six months beyond your travel date, so the deadline is earlier than the printed expiry. Photo rejections are the single most common cause of delay.", citation:"https://www.britannica.com/", difficulty:"easy" },
  { category:"science", rule:"How a hurricane forms", items:["warm ocean water evaporates","the moist air rises and cools","thunderstorms cluster and organise","a low-pressure centre forms","spiral bands wrap around the clear eye","landfall cuts off the energy source"], reveal:"The fuel is warm surface water — that is why hurricanes weaken quickly over land, and why they cannot form within about 5° of the equator, where there is no Coriolis force to spin them up.", citation:"https://www.noaa.gov/", difficulty:"hard" },
  { category:"history", rule:"The fall of the Berlin Wall and reunification", items:["reform begins in the Soviet Union","Hungary opens its border to the West (1989)","mass protests spread across East Germany","the Wall's crossings are opened (9 November 1989)","Germany is formally reunified (3 October 1990)"], reveal:"The Wall fell because of a press conference: a spokesman misread a note about relaxed travel rules and said they took effect immediately, and tens of thousands went to the checkpoints that evening.", citation:"https://www.britannica.com/", difficulty:"medium" },
];

const FERMI_BANK: FermiPuzzle[] = [
  { category:"food", units:"kcal", prompt:"How many calories are in a Big Mac?", answer:550, reveal:"US Big Mac ~563 kcal; global versions 540–590. About a third of an adult's daily 2,000 kcal budget.", citation:"https://www.mcdonalds.com/us/en-us/product/big-mac.html", difficulty:"easy" },
  { category:"space", units:"km", prompt:"How far is the Moon from Earth?", answer:384400, reveal:"~30 Earth diameters. Light takes 1.3 seconds. Apollo astronauts took ~3 days.", citation:"https://solarsystem.nasa.gov/moons/earths-moon/in-depth/", difficulty:"easy" },
  { category:"biology", units:"bones", prompt:"How many bones are in an adult human body?", answer:206, reveal:"Babies have ~300 bones that fuse -- 206 remain. Fusion, not loss.", citation:"https://www.britannica.com/science/human-skeleton", difficulty:"easy" },
  { category:"physics", units:"km/s", prompt:"What is the speed of light?", answer:299792, reveal:"~300,000 km/s. One light-second ~ 7.5 Earth equators. Nothing with mass can reach it.", citation:"https://www.britannica.com/science/speed-of-light", difficulty:"medium" },
  { category:"biology", units:"beats", prompt:"How many times does a human heart beat in a lifetime?", answer:3100000000, reveal:"75 bpm × 60 × 24 × 365 × 80 yrs ~ 3.1 billion. Published estimates range 2.5–3.5 billion.", citation:"https://www.sciencefocus.com/the-human-body/how-many-times-does-your-heart-beat-in-a-lifetime", difficulty:"hard" },
  { category:"earth", units:"%", prompt:"What fraction of Earth's water is fresh?", answer:2.5, reveal:"USGS: 97.5% saltwater. Of the 2.5% fresh, most is locked in ice. Only ~0.3% is accessible surface water.", citation:"https://www.usgs.gov/special-topics/water-science-school/science/how-much-water-there-earth", difficulty:"medium" },
  { category:"biology", units:"°C", prompt:"What is the average human body temperature?", answer:37, reveal:"Classic 98.6°F = 37°C. Modern averages 36.5–37.5°C with diurnal swing ±0.5°C.", citation:"https://www.ncbi.nlm.nih.gov/books/NBK331/", difficulty:"easy" },
  { category:"demographics", units:"people", prompt:"What is the world population? (2025 estimate)", answer:8200000000, reveal:"UN 2025 estimate: ~8.2 billion. Hit 8 billion November 2022. Growing ~0.9%/year.", citation:"https://www.un.org/en/global-issues/population", difficulty:"medium" },
  { category:"biology", units:"muscles", prompt:"How many muscles are in the human body?", answer:600, reveal:"Published counts range 600–650. Includes skeletal, smooth, and cardiac muscle.", citation:"https://www.britannica.com/science/human-muscle-system", difficulty:"medium" },
  { category:"space", units:"days", prompt:"How many days for Earth to orbit the Sun?", answer:365.25, reveal:"The 0.25 is why we have leap years. Sidereal year: 365.256 days; tropical year: 365.242 days.", citation:"https://www.britannica.com/science/year", difficulty:"easy" },
  { category:"geography", units:"km", prompt:"What is the circumference of Earth at the equator?", answer:40075, reveal:"~40,075 km. Eratosthenes calculated it within 2% in 240 BCE using shadows and geometry.", citation:"https://www.britannica.com/science/Earth-circumference", difficulty:"medium" },
  { category:"biology", units:"cells", prompt:"How many cells are in the human body?", answer:37000000000000, reveal:"~37 trillion. Bacteria on/in you outnumber your cells ~1:1. You're half human cells, half microbes.", citation:"https://www.nature.com/articles/nature.2016.19194", difficulty:"hard" },
  { category:"physics", units:"m/s²", prompt:"Acceleration due to gravity on Earth?", answer:9.8, reveal:"9.8 m/s² at sea level. Varies: ~9.78 equator, ~9.83 poles. Moon gravity is 1.6 m/s² -- about 1/6th.", citation:"https://www.britannica.com/science/gravity-physics", difficulty:"easy" },
  { category:"history", units:"years", prompt:"How old is the universe?", answer:13800000000, reveal:"~13.8 billion years from cosmic microwave background measurements. Earth is 4.5 billion -- the universe is three times older.", citation:"https://map.gsfc.nasa.gov/universe/uni_age.html", difficulty:"hard" },
  { category:"geography", units:"m", prompt:"Height of Mount Everest?", answer:8849, reveal:"8,849 m above sea level. Summit grows ~4 mm/year from tectonic collision. Equivalent to stacking ~3,000 double-decker buses.", citation:"https://www.britannica.com/place/Mount-Everest", difficulty:"easy" },
  { category:"biology", units:"km", prompt:"Total length of blood vessels in a human?", answer:100000, reveal:"~100,000 km -- circle Earth 2.5 times. Mostly capillaries, each thinner than a hair.", citation:"https://www.fi.edu/heart/blood-vessels", difficulty:"hard" },
  { category:"physics", units:"°C", prompt:"Temperature of the Sun's core?", answer:15000000, reveal:"~15 million °C. Nuclear fusion converts hydrogen to helium. At this temperature, atoms become plasma.", citation:"https://solarsystem.nasa.gov/solar-system/sun/in-depth/", difficulty:"hard" },
  { category:"food", units:"L", prompt:"How much water should an adult drink per day?", answer:2.5, reveal:"~2.5 L total (including food). The '8 glasses' rule = ~1.9 L. Individual needs vary with activity and climate.", citation:"https://www.mayoclinic.org/healthy-lifestyle/nutrition-and-healthy-eating/in-depth/water/art-20044256", difficulty:"easy" },
  { category:"space", units:"km", prompt:"Diameter of the Sun?", answer:1392700, reveal:"~1.39 million km -- 109× Earth. You could fit ~1.3 million Earths inside the Sun.", citation:"https://solarsystem.nasa.gov/solar-system/sun/in-depth/", difficulty:"medium" },
  { category:"biology", units:"years", prompt:"Average human lifespan worldwide?", answer:73, reveal:"~73 years (WHO 2024). Varies from ~54 in some countries to ~85 in others. Nearly doubled in the last century.", citation:"https://www.who.int/data/gho/data/themes/mortality-and-global-health-estimates", difficulty:"medium" },
  { category:"physics", units:"m/s", prompt:"Speed of sound in air?", answer:343, reveal:"~343 m/s at 20°C. Faster in water (~1,500 m/s). Increases ~0.6 m/s per °C. Thunder = lightning distance in km ÷ 3.", citation:"https://www.britannica.com/science/speed-of-sound-physics", difficulty:"medium" },
  { category:"geography", units:"km²", prompt:"Surface area of Earth?", answer:510100000, reveal:"~510 million km². About 71% water, 29% land. Roughly the area of 10 Jupiters' Great Red Spots.", citation:"https://www.britannica.com/science/Earth", difficulty:"medium" },
  { category:"biology", units:"neurons", prompt:"How many neurons in the human brain?", answer:86000000000, reveal:"~86 billion. Each connects to ~1,000 others = ~100 trillion synapses. Brain uses ~20 watts -- like a dim lightbulb.", citation:"https://www.nature.com/articles/nature.2012.10162", difficulty:"hard" },
  { category:"finance", units:"USD", prompt:"Apple's market cap end of 2024?", answer:3800000000000, reveal:"~$3.8 trillion. Larger than the GDP of most countries. Only US, China, Germany, Japan have bigger economies.", citation:"https://companiesmarketcap.com/apple/marketcap/", difficulty:"hard" },
  { category:"biology", units:"L", prompt:"How much blood in an adult human?", answer:5, reveal:"~5 litres. Heart pumps entire volume through the body ~once per minute at rest.", citation:"https://www.britannica.com/science/blood-biochemistry", difficulty:"easy" },
  { category:"space", units:"stars", prompt:"How many stars in the Milky Way?", answer:200000000000, reveal:"~100–400 billion. Sun is one, ~26,000 light-years from the galactic centre. And there are ~2 trillion galaxies.", citation:"https://imagine.gsfc.nasa.gov/science/objects/milkyway1.html", difficulty:"hard" },
  { category:"physics", units:"V", prompt:"Voltage of a standard AA battery?", answer:1.5, reveal:"1.5V. Car battery = 12V. Household: 120V (US) / 230V (Europe). Lightning = ~300 million volts.", citation:"https://www.britannica.com/technology/battery-electronics", difficulty:"easy" },
  { category:"geography", units:"km", prompt:"Length of the Amazon River?", answer:6400, reveal:"~6,400 km. Nile is close at ~6,650 km -- which is longest depends on measurement. Amazon carries more water than next 7 rivers combined.", citation:"https://www.britannica.com/place/Amazon-River", difficulty:"medium" },
  { category:"biology", units:"bpm", prompt:"Average resting heart rate?", answer:72, reveal:"60–100 bpm normal; ~72 average. Athletes often <60. Hummingbird: ~1,200 bpm. Blue whale: ~8 bpm.", citation:"https://www.mayoclinic.org/healthy-lifestyle/fitness/expert-answers/heart-rate/faq-20057979", difficulty:"easy" },
  { category:"time", units:"seconds", prompt:"How many seconds in a year?", answer:31536000, reveal:"60×60×24×365 = 31,536,000. A million seconds ~ 11.5 days. A billion seconds ~ 31.7 years.", citation:"https://www.nist.gov/pml/time-and-frequency-division", difficulty:"easy" },
  { category:"biology", units:"kg", prompt:"Mass of an adult African elephant?", answer:6000, reveal:"~6,000 kg (6 tonnes). Largest land animal. Blue whale: up to 200 tonnes -- over 30× heavier.", citation:"https://www.worldwildlife.org/species/african-elephant", difficulty:"medium" },
  { category:"physics", units:"m", prompt:"Wavelength of visible red light?", answer:0.0000007, reveal:"~700 nanometres = 7×10⁻⁷ m. Violet = ~400 nm. The entire visible spectrum spans less than one octave.", citation:"https://www.britannica.com/science/color/The-visible-spectrum", difficulty:"hard" },
  { category:"demographics", units:"people", prompt:"Population of India? (2025)", answer:1450000000, reveal:"~1.45 billion -- world's most populous, surpassing China in 2023. ~17.8% of all humans live in India.", citation:"https://www.un.org/en/global-issues/population", difficulty:"medium" },
  { category:"food", units:"beans", prompt:"How many coffee beans for one espresso?", answer:70, reveal:"~70 beans for a double shot (~18g ground). One tree produces ~1 kg roasted coffee per year.", citation:"https://www.ncausa.org/About-Coffee/10-Steps-from-Seed-to-Cup", difficulty:"medium" },
  { category:"space", units:"ly", prompt:"Distance to nearest star (after the Sun)?", answer:4.24, reveal:"Proxima Centauri: 4.24 light-years. At Voyager 1 speed (17 km/s), it would take ~75,000 years.", citation:"https://www.space.com/18090-alpha-centauri-nearest-star-system.html", difficulty:"medium" },
  { category:"history", units:"years", prompt:"How long did the Roman Empire last?", answer:500, reveal:"~500 years (27 BCE–476 CE Western). Eastern (Byzantine) Empire lasted until 1453 -- nearly 1,500 years total.", citation:"https://www.britannica.com/place/Roman-Empire", difficulty:"medium" },
  { category:"biology", units:"L", prompt:"How much air do lungs hold? (total capacity)", answer:6, reveal:"~6 litres total lung capacity. Tidal volume (normal breath) = ~0.5 L. Elite athletes can have 8+ L capacity.", citation:"https://www.britannica.com/science/lung-volume", difficulty:"medium" },
  { category:"geography", units:"m", prompt:"Depth of the Mariana Trench?", answer:11000, reveal:"~11,000 m (11 km). If Mount Everest were placed at the bottom, its peak would still be 2 km underwater.", citation:"https://www.britannica.com/place/Mariana-Trench", difficulty:"medium" },
  { category:"physics", units:"°C below zero", prompt:"How many degrees below zero is absolute zero?", answer:273.15, reveal:"Absolute zero is −273.15°C = 0 Kelvin. At this temperature, atoms have minimum possible energy -- all thermal motion stops. Never actually reached.", citation:"https://www.britannica.com/science/absolute-zero", difficulty:"medium" },
  { category:"food", units:"kg", prompt:"How much food does an average adult eat per year?", answer:900, reveal:"~900 kg (~2,000 lbs). About 2.5 kg per day including water content. Roughly the weight of a small car.", citation:"https://www.ers.usda.gov/data-products/food-availability-per-capita-data-system/", difficulty:"hard" },
  { category:"art", units:"keys", prompt:"How many keys are on a standard piano?", answer:88, reveal:"88 keys: 52 white and 36 black, spanning just over seven octaves. Older pianos were built with 85 or fewer.", citation:"https://www.britannica.com/", difficulty:"easy" },
  { category:"art", units:"strings", prompt:"How many strings does a standard violin have?", answer:4, reveal:"Four strings — G, D, A and E — tuned in fifths. Fewer strings than a guitar, but a far wider expressive range in trained hands.", citation:"https://www.britannica.com/", difficulty:"easy" },
  { category:"music", units:"strings", prompt:"How many strings does a standard acoustic guitar have?", answer:6, reveal:"Six, tuned E–A–D–G–B–E. Twelve-string guitars double them in pairs, with the lower four pairs tuned in octaves.", citation:"https://www.britannica.com/", difficulty:"easy" },
  { category:"sports", units:"players", prompt:"How many players from one team are on a football (soccer) pitch at a time?", answer:11, reveal:"Eleven per side including the goalkeeper. Law 3 of the Laws of the Game fixes the number; a match cannot start with fewer than seven.", citation:"https://www.fifa.com/en/tournaments", difficulty:"easy" },
  { category:"sports", units:"squares", prompt:"How many squares are on a standard chessboard?", answer:64, reveal:"64 squares in an 8×8 grid, 32 light and 32 dark. A full set of move sequences is measured in the tens of billions of possibilities after only a few moves.", citation:"https://www.fide.com/", difficulty:"medium" },
  { category:"sports", units:"players", prompt:"How many players from one team are on a basketball court at a time?", answer:5, reveal:"Five per team. The sport is built around that number: with ten players on a much smaller floor than football, spacing is everything.", citation:"https://www.olympics.com/en/olympic-games", difficulty:"easy" },
  { category:"sports", units:"rings", prompt:"How many rings are on the Olympic flag?", answer:5, reveal:"Five interlocking rings on a white field, representing the five inhabited continents that took part when Pierre de Coubertin designed it in 1913.", citation:"https://www.olympics.com/en/olympic-games", difficulty:"easy" },
  { category:"sports", units:"gold medals", prompt:"How many Olympic gold medals did swimmer Michael Phelps win?", answer:23, reveal:"23 golds across four Games, plus 3 silver and 2 bronze — 28 medals in total, more than any other Olympian.", citation:"https://www.olympics.com/en/olympic-games", difficulty:"medium" },
  { category:"time", units:"minutes", prompt:"How many minutes are in one day?", answer:1440, reveal:"24 × 60 = 1,440 minutes. A useful anchor: 1,000 minutes is a bit under 17 hours, and a million seconds is only about 11.6 days.", citation:"https://www.nist.gov/pml/time-and-frequency-division", difficulty:"easy" },
  { category:"time", units:"days", prompt:"How many days are in a leap year?", answer:366, reveal:"366 — one extra day in February. Leap years keep the calendar aligned with Earth's 365.25-day orbit; century years skip the leap day unless divisible by 400.", citation:"https://www.nist.gov/pml/time-and-frequency-division", difficulty:"easy" },
  { category:"demographics", units:"member states", prompt:"How many member states are in the United Nations?", answer:193, reveal:"193 member states, plus two permanent observer states. South Sudan was the most recent addition, in 2011.", citation:"https://www.un.org/en/about-us/member-states", difficulty:"medium" },
  { category:"demographics", units:"people", prompt:"How many people live in the Tokyo metropolitan area?", answer:37000000, reveal:"About 37 million people — the largest urban agglomeration on Earth, and more than the entire population of Canada.", citation:"https://www.un.org/en/global-issues/population", difficulty:"hard" },
  { category:"space", units:"moons", prompt:"How many moons does Mars have?", answer:2, reveal:"Two: Phobos and Deimos. Both are tiny, irregular lumps — probably captured asteroids — and Phobos is slowly spiralling in toward the planet.", citation:"https://solarsystem.nasa.gov/planets/overview/", difficulty:"easy" },
  { category:"space", units:"km", prompt:"What is the average distance from Earth to the Sun?", answer:149600000, reveal:"About 149.6 million km — one astronomical unit, now fixed by definition at exactly 149,597,870.7 km. Sunlight covers it in about 8 minutes 20 seconds.", citation:"https://solarsystem.nasa.gov/planets/overview/", difficulty:"medium" },
  { category:"biology", units:"teeth", prompt:"How many teeth does a typical adult human have?", answer:32, reveal:"32 including the four wisdom teeth — 16 upper and 16 lower. Most adults lose or have the wisdom teeth removed, leaving 28.", citation:"https://www.cdc.gov/oral-health", difficulty:"easy" },
  { category:"biology", units:"chambers", prompt:"How many chambers does the human heart have?", answer:4, reveal:"Four: two atria that receive blood and two ventricles that pump it. The left ventricle does the heavy lifting, driving blood through the whole body.", citation:"https://www.nhlbi.nih.gov/health/heart", difficulty:"easy" },
  { category:"biology", units:"chromosomes", prompt:"How many chromosomes are in a typical human cell?", answer:46, reveal:"46 chromosomes in 23 pairs — one of each pair from each parent. Sex cells carry 23; a fertilised egg restores the full set.", citation:"https://www.genome.gov/about-genomics/fact-sheets", difficulty:"medium" },
  { category:"biology", units:"bones", prompt:"How many bones are in the adult human foot?", answer:26, reveal:"26 bones per foot — over a quarter of all the bones in the body. Babies start with more; several fuse during childhood.", citation:"https://www.britannica.com/science/human-skeleton", difficulty:"hard" },
  { category:"biology", units:"km/h", prompt:"How fast can a cheetah run at full sprint?", answer:100, reveal:"Around 100 km/h over short bursts — the fastest land animal. It can only hold that for a few hundred metres before overheating.", citation:"https://www.iucnredlist.org/", difficulty:"medium" },
  { category:"geography", units:"m", prompt:"How tall is the Burj Khalifa?", answer:828, reveal:"828 m — more than 160 storeys, and the tallest structure ever built. Its own weight required changes mid-construction because the original design was unstable at that height.", citation:"https://www.burjkhalifa.ae/en/", difficulty:"medium" },
  { category:"geography", units:"km", prompt:"How long is the Great Wall of China, measured end to end?", answer:21196, reveal:"About 21,196 km counting every branch and the trenches and natural barriers — the single-line main wall is roughly 8,850 km.", citation:"https://whc.unesco.org/en/list/438", difficulty:"hard" },
  { category:"art", units:"lines", prompt:"How many lines are in a Shakespearean sonnet?", answer:14, reveal:"14 lines in three quatrains plus a couplet, rhymed abab cdcd efef gg. The turn — the argument's reversal — usually lands at line 9 or 13.", citation:"https://www.britannica.com/", difficulty:"medium" },
];

// ─── Weekly scheduler ─────────────────────────────────────────────────────

function getDayOfWeek(date: Date): number {
  // 0 = Sunday, 1 = Monday, ..., 6 = Saturday
  return date.getDay();
}

export function generateOrderleForDate(date: Date): OrderlePuzzle {
  const dow = getDayOfWeek(date);
  let category: string;

  if (dow === 1) { category = "cooking"; }
  else if (dow === 2) { category = "science"; }
  else if (dow === 3) { category = "history"; }
  else if (dow === 4) { category = "grammar"; }
  else if (dow === 5) { category = "everyday"; }
  else if (dow === 6) { category = "mixed"; }
  else { category = "biology"; } // Sunday

  const pool = ORDERLE_BANK.filter(p => p.category === category);
  // Deterministic pick based on date
  const weekNum = Math.floor((date.getTime() - new Date('2026-01-05').getTime()) / (7 * 86400000));
  return pool[Math.abs(weekNum) % pool.length];
}

export function generateFermiForDate(date: Date): FermiPuzzle {
  const weekNum = Math.floor((date.getTime() - new Date('2026-01-05').getTime()) / (7 * 86400000));
  // Simple rotation through the bank
  return FERMI_BANK[Math.abs(weekNum) % FERMI_BANK.length];
}

// ─── Validation ───────────────────────────────────────────────────────────

export function validateOrderlePuzzle(p: OrderlePuzzle): string[] {
  const errors: string[] = [];
  if (!p.items || p.items.length < 3) errors.push("Needs at least 3 items");
  if (!p.rule) errors.push("Missing rule");
  if (!p.reveal || p.reveal.length < 20) errors.push("Reveal too short (min 20 chars)");
  if (!p.citation) errors.push("Missing citation");
  if (new Set(p.items).size !== p.items.length) errors.push("Duplicate items");
  return errors;
}

export function validateFermiPuzzle(p: FermiPuzzle): string[] {
  const errors: string[] = [];
  if (!p.prompt) errors.push("Missing prompt");
  if (!isFinite(p.answer) || p.answer <= 0) errors.push("Answer must be positive number");
  if (!p.reveal || p.reveal.length < 20) errors.push("Reveal too short");
  if (!p.citation) errors.push("Missing citation");
  if (!p.units) errors.push("Missing units");
  return errors;
}

export function validateAll(): { orderle: number; fermi: number; olErrors: number; fmErrors: number } {
  let olErrors = 0, fmErrors = 0;
  for (const p of ORDERLE_BANK) olErrors += validateOrderlePuzzle(p).length;
  for (const p of FERMI_BANK) fmErrors += validateFermiPuzzle(p).length;
  return { orderle: ORDERLE_BANK.length, fermi: FERMI_BANK.length, olErrors, fmErrors };
}

// Export the full banks for static export
export { ORDERLE_BANK, FERMI_BANK };
